version: "3.8"

services:

  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev

    ports:
      - 3000:3000

    container_name: muitnt-client

    networks:
      - muitnt-stack-net

    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public

    restart: "always"

    stdin_open: true
    tty: true

networks:
  muitnt-stack-net:
    driver: bridge
