version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    ports:
      - 3006:3006
    container_name: muitnt-client
    networks:
      - muitnt-stack-net
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    restart: always
    stdin_open: true
    tty: true

  server:
    container_name: server
    build:
        context: ./server
        target: development
        dockerfile: ./dockerfile.dev
    command: npm run start:debug
    ports:
        - 3001:3001
        - 9229:9229
        - 8000:8000
        - 1935:1935
    networks:
        - muitnt-stack-net
    volumes:
        - ./server:/usr/src/app
        - ./uploads:/usr/src/uploads
    restart: unless-stopped

  db:
    container_name: mysqlcontainer_dev
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    command: [ --character-set-server=utf8, --collation-server=utf8_persian_ci, --max-allowed-packet=524288000, --default-authentication-plugin=mysql_native_password]
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_vol:/var/lib/mysql
      - ./server/docker_mysql_init/init:/docker-entrypoint-initdb.d
    expose:
      - 3306
    networks:
      - muitnt-stack-net

volumes:
  db_vol:
    driver: local

networks:
  muitnt-stack-net:
    driver: bridge

