version: '3.8'
services:
  db:
    image: mysql
    container_name: mysqlcontainer
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysqldb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306
    networks:
      - mysql_dev_db_network

volumes:
  db:
    driver: local

networks:
  mysql_dev_db_network:
    driver: bridge
