version: '3.8'
services:
  db:
    container_name: mysqlcontainer
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=dev_db
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev_password
        - MYSQL_TEST_DATABASE=test_db
        - MYSQL_TEST_USER=test
        - MYSQL_TEST_PASSWORD=test_password
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev_password
      - MYSQL_TEST_DATABASE=test_db
      - MYSQL_TEST_USER=test
      - MYSQL_TEST_PASSWORD=test_password
    # restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    expose:
      - 3306
    networks:
      - mysql_dev_db_network

volumes:
  db:
    driver: local

networks:
  mysql_dev_db_network:
    driver: bridge
